### PR TITLE
Filter and internationalisation of the author name

### PR DESCRIPTION
**Pull request by smeric**
Hi,

This is a proposal for adding a filter and internationalisation to the author name diplay (collection composant).

I needed this to display multiple authors instead of only the default one.

Thanks.

Seb.

### CODE REVIEW

**Comment by michaelbeil** [comment]
:+1:

**Comment by michaelbeil** [comment]
Thanks @smeric!

**Comment by smeric** [comment]
you're welcome :)
thanks to you and all the aesop team !

**Comment by michaelbeil** [comment]
You bet!

**Pull request merged**
